### ISSUE TITLE
Concats odd things together...

### ISSUE THREAD

**Issue by paulcollinsiii** [patrickpietens/gulp-concat-vendor#3]
If your bower.json says to install angular and bootstrap then this will concat angular.js and bootstrap.less together.

**Comment by AndrwM** [comment]
+1

**Comment by Leolik** [comment]
+1

**Comment by rcorrie** [comment]
I have an open pull request on this issue, check it out [here](https://github.com/patrickpietens/gulp-concat-vendor/pull/5).

Hopefully it gets merged in as this is a big annoyance to an otherwise awesome gulp module.

**Comment by patrickpietens** [comment]
I'm very busy at the moment. Therefor I haven't had the time to look at this. Sorry guys. Anyways, thnx to @rcorrie we have a fix now. @rcorrie Just merged your PR. Thnx for your help.
